Insert into cidade (nome, estado_id) value ('Agudos do Sul', 1),
    ('Almirante Tamandaré', 1),
    ('Altamira do Paraná', 1),
    ('Alto Paraíso', 1),
    ('Alto Paraná', 1),
    ('Alto Piquiri', 1),
    ('Altônia', 1),
    ('Alvorada do Sul', 1),
    ('Amaporã', 1),
    ('Ampére', 1),
    ('Anahy', 1),
    ('Andirá', 1),
    ('Ângulo', 1),
    ('Antonina', 1),
    ('Antônio Olinto', 1),
    ('Apucarana', 1),
    ('Arapongas', 1),
    ('Arapoti', 1),
    ('Arapuã', 1),
    ('Araruna', 1),
    ('Araucária', 1),
    ('Ariranha do Ivaí', 1),
    ('Assaí', 1),
    ('Assis Chateaubriand', 1),
    ('Astorga', 1),
    ('Atalaia', 1),
    ('Balsa Nova', 1),
    ('Bandeirantes', 1),
    ('Barbosa Ferraz', 1),
    ('Barra do Jacaré', 1),
    ('Barracão', 1),
    ('Bela Vista da Caroba', 1),
    ('Bela Vista do Paraíso', 1),
    ('Bituruna', 1),
    ('Boa Esperança', 1),
    ('Boa Esperança do Iguaçu', 1),
    ('Boa Ventura de São Roque', 1),
    ('Boa Vista da Aparecida', 1),
    ('Bocaiúva do Sul', 1),
    ('Bom Jesus do Sul', 1),
    ('Bom Sucesso', 1),
    ('Bom Sucesso do Sul', 1),
    ('Borrazópolis', 1),
    ('Braganey', 1),
    ('Brasilândia do Sul', 1),
    ('Cafeara', 1),
    ('Cafelândia', 1),
    ('Cafezal do Sul', 1),
    ('Califórnia', 1),
    ('Cambará', 1),
    ('Cambé', 1),
    ('Cambira', 1),
    ('Campina da Lagoa', 1),
    ('Campina do Simão', 1),
    ('Campina Grande do Sul', 1),
    ('Campo Bonito', 1),
    ('Campo do Tenente', 1),
    ('Campo Largo', 1),
    ('Campo Magro', 1),
    ('Campo Mourão', 1),
    ('Cândido de Abreu', 1),
    ('Candói', 1),
    ('Cantagalo', 1),
    ('Capanema', 1),
    ('Capitão Leônidas Marques', 1),
    ('Carambeí', 1),
    ('Carlópolis', 1),
    ('Cascavel', 1),
    ('Castro', 1),
    ('Catanduvas', 1),
    ('Centenário do Sul', 1),
    ('Cerro Azul', 1),
    ('Céu Azul', 1),
    ('Chopinzinho', 1),
    ('Cianorte', 1),
    ('Cidade Gaúcha', 1),
    ('Clevelândia', 1),
    ('Colombo', 1),
    ('Colorado', 1),
    ('Congonhinhas', 1),
    ('Conselheiro Mairinck', 1),
    ('Contenda', 1),
    ('Corbélia', 1),
    ('Cornélio Procópio', 1),
    ('Coronel Domingos Soares', 1),
    ('Coronel Vivida', 1),
    ('Corumbataí do Sul', 1),
    ('Cruz Machado', 1),
    ('Cruzeiro do Iguaçu', 1),
    ('Cruzeiro do Oeste', 1),
    ('Cruzeiro do Sul', 1),
    ('Cruzmaltina', 1),
    ('Curitiba', 1),
    ('Curiúva', 1),
    ('Diamante d`Oeste', 1),
    ('Diamante do Norte', 1),
    ('Diamante do Sul', 1),
    ('Dois Vizinhos', 1),
    ('Douradina', 1),
    ('Doutor Camargo', 1),
    ('Doutor Ulysses', 1),
    ('Enéas Marques', 1),
    ('Engenheiro Beltrão', 1),
    ('Entre Rios do Oeste', 1),
    ('Esperança Nova', 1),
    ('Espigão Alto do Iguaçu', 1),
    ('Farol', 1),
    ('Faxinal', 1),
    ('Fazenda Rio Grande', 1),
    ('Fênix', 1),
    ('Fernandes Pinheiro', 1),
    ('Figueira', 1),
    ('Flor da Serra do Sul', 1),
    ('Floraí', 1),
    ('Floresta', 1),
    ('Florestópolis', 1),
    ('Flórida', 1),
    ('Formosa do Oeste', 1),
    ('Foz do Iguaçu', 1),
    ('Foz do Jordão', 1),
    ('Francisco Alves', 1),
    ('Francisco Beltrão', 1),
    ('General Carneiro', 1), ('Godoy Moreira', 1),
    ('Goioerê', 1),
    ('Goioxim', 1),
    ('Grandes Rios', 1),
    ('Guaíra', 1),
    ('Guairaçá', 1),
    ('Guamiranga', 1),
    ('Guapirama', 1),
    ('Guaporema', 1),
    ('Guaraci', 1),
    ('Guaraniaçu', 1),
    ('Guarapuava', 1),
    ('Guaraqueçaba', 1),
    ('Guaratuba', 1),
    ('Honório Serpa', 1),
    ('Ibaiti', 1),
    ('Ibema', 1),
    ('Ibiporã', 1),
    ('Icaraíma', 1),
    ('Iguaraçu', 1),
    ('Iguatu', 1),
    ('Imbaú', 1),
    ('Imbituva', 1),
    ('Inácio Martins', 1),
    ('Inajá', 1),
    ('Indianópolis', 1),
    ('Ipiranga', 1),
    ('Iporã', 1),
    ('Iracema do Oeste', 1),
    ('Irati', 1),
    ('Iretama', 1),
    ('Itaguajé', 1),
    ('Itaipulândia', 1),
    ('Itambaracá', 1),
    ('Itambé', 1),
    ('Itapejara d`Oeste', 1),
    ('Itaperuçu', 1),
    ('Itaúna do Sul', 1),
    ('Ivaí', 1),
    ('Ivaiporã', 1),
    ('Ivaté', 1),
    ('Ivatuba', 1),
    ('Jaboti', 1),
    ('Jacarezinho', 1),
    ('Jaguapitã', 1),
    ('Jaguariaíva', 1),
    ('Jandaia do Sul', 1),
    ('Janiópolis', 1),
    ('Japira', 1),
    ('Japurá', 1),
    ('Jardim Alegre', 1),
    ('Jardim Olinda', 1),
    ('Jataizinho', 1),
    ('Jesuítas', 1),
    ('Joaquim Távora', 1),
    ('Jundiaí do Sul', 1),
    ('Juranda', 1),
    ('Jussara', 1),
    ('Kaloré', 1),
    ('Lapa', 1),
    ('Laranjal', 1),
    ('Laranjeiras do Sul', 1),
    ('Leópolis', 1),
    ('Lidianópolis', 1),
    ('Lindoeste', 1),
    ('Loanda', 1),
    ('Lobato', 1),
    ('Londrina', 1),
    ('Luiziana', 1),
    ('Lunardelli', 1),
    ('Lupionópolis', 1),
    ('Mallet', 1),
    ('Mamborê', 1),
    ('Mandaguaçu', 1),
    ('Mandaguari', 1),
    ('Mandirituba', 1),
    ('Manfrinópolis', 1),
    ('Mangueirinha', 1),
    ('Manoel Ribas', 1),
    ('Marechal Cândido Rondon', 1),
    ('Maria Helena', 1),
    ('Marialva', 1),
    ('Marilândia do Sul', 1),
    ('Marilena', 1),
    ('Mariluz', 1),
    ('Maringá', 1),
    ('Mariópolis', 1),
    ('Maripá', 1),
    ('Marmeleiro', 1),
    ('Marquinho', 1),
    ('Marumbi', 1),
    ('Matelândia', 1),
    ('Matinhos', 1),
    ('Mato Rico', 1),
    ('Mauá da Serra', 1),
    ('Medianeira', 1),
    ('Mercedes', 1),
    ('Mirador', 1),
    ('Miraselva', 1),
    ('Missal', 1),
    ('Moreira Sales', 1),
    ('Morretes', 1),
    ('Munhoz de Melo', 1),
    ('Nossa Senhora das Graças', 1),
    ('Nova Aliança do Ivaí', 1),
    ('Nova América da Colina', 1),
    ('Nova Aurora', 1),
    ('Nova Cantu', 1),
    ('Nova Esperança', 1),
    ('Nova Esperança do Sudoeste', 1),
    ('Nova Fátima', 1),
    ('Nova Laranjeiras', 1),
    ('Nova Londrina', 1),
    ('Nova Olímpia', 1),
    ('Nova Prata do Iguaçu', 1),
    ('Nova Santa Bárbara', 1),
    ('Nova Santa Rosa', 1),
    ('Nova Tebas', 1),
    ('Novo Itacolomi', 1),
    ('Ortigueira', 1),
    ('Ourizona', 1),
    ('Ouro Verde do Oeste', 1),
    ('Paiçandu', 1),
    ('Palmas', 1),
    ('Palmeira', 1),
    ('Palmital', 1),
    ('Palotina', 1),
    ('Paraíso do Norte', 1),
    ('Paranacity', 1),
    ('Paranaguá', 1),
    ('Paranapoema', 1),
    ('Paranavaí', 1),
    ('Pato Bragado', 1),
    ('Pato Branco', 1),
    ('Paula Freitas', 1),
    ('Paulo Frontin', 1),
    ('Peabiru', 1),
    ('Perobal', 1),
    ('Pérola', 1),
    ('Pérola d`Oeste', 1),
    ('Piên', 1),
    ('Pinhais', 1),
    ('Pinhal de São Bento', 1),
    ('Pinhalão', 1),
    ('Pinhão', 1),
    ('Piraí do Sul', 1),
    ('Piraquara', 1),
    ('Pitanga', 1),
    ('Pitangueiras', 1),
    ('Planaltina do Paraná', 1),
    ('Planalto', 1),
    ('Ponta Grossa', 1),
    ('Pontal do Paraná', 1),
    ('Porecatu', 1),
    ('Porto Amazonas', 1),
    ('Porto Barreiro', 1),
    ('Porto Rico', 1),
    ('Porto Vitória', 1),
    ('Prado Ferreira', 1),
    ('Pranchita', 1),
    ('Presidente Castelo Branco', 1),
    ('Primeiro de Maio', 1),
    ('Prudentópolis', 1),
    ('Quarto Centenário', 1),
    ('Quatiguá', 1),
    ('Quatro Barras', 1),
    ('Quatro Pontes', 1),
    ('Quedas do Iguaçu', 1),
    ('Querência do Norte', 1),
    ('Quinta do Sol', 1),
    ('Quitandinha', 1),
    ('Ramilândia', 1),
    ('Rancho Alegre', 1),
    ('Rancho Alegre d`Oeste', 1),
    ('Realeza', 1),
    ('Rebouças', 1),
    ('Renascença', 1),
    ('Reserva', 1),
    ('Reserva do Iguaçu', 1),
    ('Ribeirão Claro', 1),
    ('Ribeirão do Pinhal', 1),
    ('Rio Azul', 1),
    ('Rio Bom', 1),
    ('Rio Bonito do Iguaçu', 1),
    ('Rio Branco do Ivaí', 1),
    ('Rio Branco do Sul', 1),
    ('Rio Negro', 1),
    ('Rolândia', 1),
    ('Roncador', 1),
    ('Rondon', 1),
    ('Rosário do Ivaí', 1),
    ('Sabáudia', 1),
    ('Salgado Filho', 1),
    ('Salto do Itararé', 1),
    ('Salto do Lontra', 1),
    ('Santa Amélia', 1),
    ('Santa Cecília do Pavão', 1),
    ('Santa Cruz de Monte Castelo', 1),
    ('Santa Fé', 1),
    ('Santa Helena', 1),
    ('Santa Inês', 1),
    ('Santa Isabel do Ivaí', 1),
    ('Santa Izabel do Oeste', 1),
    ('Santa Lúcia', 1),
    ('Santa Maria do Oeste', 1),
    ('Santa Mariana', 1),
    ('Santa Mônica', 1),
    ('Santa Tereza do Oeste', 1),
    ('Santa Terezinha de Itaipu', 1),
    ('Santana do Itararé', 1),
    ('Santo Antônio da Platina', 1),
    ('Santo Antônio do Caiuá', 1),
    ('Santo Antônio do Paraíso', 1),
    ('Santo Antônio do Sudoeste', 1),
    ('Santo Inácio', 1),
    ('São Carlos do Ivaí', 1),
    ('São Jerônimo da Serra', 1),
    ('São João', 1),
    ('São João do Caiuá', 1),
    ('São João do Ivaí', 1),
    ('São João do Triunfo', 1),
    ('São Jorge d`Oeste', 1),
    ('São Jorge do Ivaí', 1),
    ('São Jorge do Patrocínio', 1),
    ('São José da Boa Vista', 1),
    ('São José das Palmeiras', 1),
    ('São José dos Pinhais', 1),
    ('São Manoel do Paraná', 1),
    ('São Mateus do Sul', 1),
    ('São Miguel do Iguaçu', 1),
    ('São Pedro do Iguaçu', 1),
    ('São Pedro do Ivaí', 1),
    ('São Pedro do Paraná', 1),
    ('São Sebastião da Amoreira', 1),
    ('São Tomé', 1),
    ('Sapopema', 1),
    ('Sarandi', 1),
    ('Saudade do Iguaçu', 1),
    ('Sengés', 1),
    ('Serranópolis do Iguaçu', 1),
    ('Sertaneja', 1),
    ('Sertanópolis', 1),
    ('Siqueira Campos', 1),
    ('Sulina', 1),
    ('Tamarana', 1),
    ('Tamboara', 1),
    ('Tapejara', 1),
    ('Tapira', 1),
    ('Teixeira Soares', 1),
    ('Telêmaco Borba', 1),
    ('Terra Boa', 1),
    ('Terra Rica', 1),
    ('Terra Roxa', 1),
    ('Tibagi', 1),
    ('Tijucas do Sul', 1),
    ('Toledo', 1),
    ('Tomazina', 1),
    ('Três Barras do Paraná', 1),
    ('Tunas do Paraná', 1),
    ('Tuneiras do Oeste', 1),
    ('Tupãssi', 1),
    ('Turvo', 1),
    ('Ubiratã', 1),
    ('Umuarama', 1),
    ('União da Vitória', 1),
    ('Uniflor', 1),
    ('Uraí', 1),
    ('Ventania', 1),
    ('Vera Cruz do Oeste', 1),
    ('Verê', 1),
    ('Virmond', 1),
    ('Vitorino', 1),
    ('Wenceslau Braz', 1),
    ('Xambrê', 1),
    ('Aceguá', 2),
    ('Água Santa', 2),
    ('Agudo', 2),
    ('Ajuricaba', 2),
    ('Alecrim', 2),
    ('Alegrete', 2),
    ('Alegria', 2),
    ('Almirante Tamandaré do Sul', 2),
    ('Alpestre', 2),
    ('Alto Alegre', 2),
    ('Alto Feliz', 2),
    ('Alvorada', 2),
    ('Amaral Ferrador', 2),
    ('Ametista do Sul', 2),
    ('André da Rocha', 2),
    ('Anta Gorda', 2),
    ('Antônio Prado', 2),
    ('Arambaré', 2),
    ('Araricá', 2),
    ('Aratiba', 2),
    ('Arroio do Meio', 2),
    ('Arroio do Padre', 2),
    ('Arroio do Sal', 2),
    ('Arroio do Tigre', 2),
    ('Arroio dos Ratos', 2),
    ('Arroio Grande', 2),
    ('Arvorezinha', 2),
    ('Augusto Pestana', 2),
    ('Áurea', 2),
    ('Bagé', 2),
    ('Balneário Pinhal', 2),
    ('Barão', 2),
    ('Barão de Cotegipe', 2),
    ('Barão do Triunfo', 2),
    ('Barra do Guarita', 2),
    ('Barra do Quaraí', 2),
    ('Barra do Ribeiro', 2),
    ('Barra do Rio Azul', 2),
    ('Barra Funda', 2),
    ('Barracão', 2),
    ('Barros Cassal', 2),
    ('Benjamin Constant do Sul', 2),
    ('Bento Gonçalves', 2),
    ('Boa Vista das Missões', 2),
    ('Boa Vista do Buricá', 2),
    ('Boa Vista do Cadeado', 2),
    ('Boa Vista do Incra', 2),
    ('Boa Vista do Sul', 2),
    ('Bom Jesus', 2),
    ('Bom Princípio', 2),
    ('Bom Progresso', 2),
    ('Bom Retiro do Sul', 2),
    ('Boqueirão do Leão', 2),
    ('Bossoroca', 2),
    ('Bozano', 2),
    ('Braga', 2),
    ('Brochier', 2),
    ('Butiá', 2),
    ('Caçapava do Sul', 2),
    ('Cacequi', 2),
    ('Cachoeira do Sul', 2),
    ('Cachoeirinha', 2),
    ('Cacique Doble', 2),
    ('Caibaté', 2),
    ('Caiçara', 2),
    ('Camaquã', 2),
    ('Camargo', 2),
    ('Cambará do Sul', 2),
    ('Campestre da Serra', 2),
    ('Campina das Missões', 2),
    ('Campinas do Sul', 2),
    ('Campo Bom', 2),
    ('Campo Novo', 2),
    ('Campos Borges', 2),
    ('Candelária', 2),
    ('Cândido Godói', 2),
    ('Candiota', 2),
    ('Canela', 2),
    ('Canguçu', 2),
    ('Canoas', 2),
    ('Canudos do Vale', 2),
    ('Capão Bonito do Sul', 2),
    ('Capão da Canoa', 2),
    ('Capão do Cipó', 2),
    ('Capão do Leão', 2),
    ('Capela de Santana', 2),
    ('Capitão', 2),
    ('Capivari do Sul', 2),
    ('Caraá', 2),
    ('Carazinho', 2),
    ('Carlos Barbosa', 2),
    ('Carlos Gomes', 2),
    ('Casca', 2),
    ('Caseiros', 2),
    ('Catuípe', 2),
    ('Caxias do Sul', 2),
    ('Centenário', 2),
    ('Cerrito', 2),
    ('Cerro Branco', 2),
    ('Cerro Grande', 2),
    ('Cerro Grande do Sul', 2),
    ('Cerro Largo', 2),
    ('Chapada', 2),
    ('Charqueadas', 2),
    ('Charrua', 2),
    ('Chiapeta', 2),
    ('Chuí', 2),
    ('Chuvisca', 2),
    ('Cidreira', 2),
    ('Ciríaco', 2),
    ('Colinas', 2),
    ('Colorado', 2),
    ('Condor', 2),
    ('Constantina', 2),
    ('Coqueiro Baixo', 2),
    ('Coqueiros do Sul', 2),
    ('Coronel Barros', 2),
    ('Coronel Bicaco', 2),
    ('Coronel Pilar', 2),
    ('Cotiporã', 2),
    ('Coxilha', 2),
    ('Crissiumal', 2),
    ('Cristal', 2),
    ('Cristal do Sul', 2),
    ('Cruz Alta', 2),
    ('Cruzaltense', 2),
    ('Cruzeiro do Sul', 2),
    ('David Canabarro', 2),
    ('Derrubadas', 2),
    ('Dezesseis de Novembro', 2),
    ('Dilermando de Aguiar', 2),
    ('Dois Irmãos', 2),
    ('Dois Irmãos das Missões', 2),
    ('Dois Lajeados', 2),
    ('Dom Feliciano', 2),
    ('Dom Pedrito', 2),
    ('Dom Pedro de Alcântara', 2),
    ('Dona Francisca', 2),
    ('Doutor Maurício Cardoso', 2),
    ('Doutor Ricardo', 2),
    ('Eldorado do Sul', 2),
    ('Encantado', 2),
    ('Encruzilhada do Sul', 2),
    ('Engenho Velho', 2),
    ('Entre Rios do Sul', 2),
    ('Entre-Ijuís', 2),
    ('Erebango', 2),
    ('Erechim', 2),
    ('Ernestina', 2),
    ('Erval Grande', 2),
    ('Erval Seco', 2),
    ('Esmeralda', 2),
    ('Esperança do Sul', 2),
    ('Espumoso', 2),
    ('Estação', 2),
    ('Estância Velha', 2),
    ('Esteio', 2),
    ('Estrela', 2),
    ('Estrela Velha', 2),
    ('Eugênio de Castro', 2),
    ('Fagundes Varela', 2),
    ('Farroupilha', 2),
    ('Faxinal do Soturno', 2),
    ('Faxinalzinho', 2),
    ('Fazenda Vilanova', 2),
    ('Feliz', 2),
    ('Flores da Cunha', 2),
    ('Floriano Peixoto', 2),
    ('Fontoura Xavier', 2),
    ('Formigueiro', 2),
    ('Forquetinha', 2),
    ('Fortaleza dos Valos', 2),
    ('Frederico Westphalen', 2),
    ('Garibaldi', 2),
    ('Garruchos', 2),
    ('Gaurama', 2),
    ('General Câmara', 2),
    ('Gentil', 2),
    ('Getúlio Vargas', 2),
    ('Giruá', 2),
    ('Glorinha', 2),
    ('Gramado', 2),
    ('Gramado dos Loureiros', 2),
    ('Gramado Xavier', 2),
    ('Gravataí', 2),
    ('Guabiju', 2),
    ('Guaíba', 2),
    ('Guaporé', 2),
    ('Guarani das Missões', 2),
    ('Harmonia', 2),
    ('Herval', 2),
    ('Herveiras', 2),
    ('Horizontina', 2),
    ('Hulha Negra', 2),
    ('Humaitá', 2),
    ('Ibarama', 2),
    ('Ibiaçá', 2),
    ('Ibiraiaras', 2),
    ('Ibirapuitã', 2),
    ('Ibirubá', 2),
    ('Igrejinha', 2),
    ('Ijuí', 2),
    ('Ilópolis', 2),
    ('Imbé', 2),
    ('Imigrante', 2),
    ('Independência', 2),
    ('Inhacorá', 2),
    ('Ipê', 2),
    ('Ipiranga do Sul', 2),
    ('Iraí', 2),
    ('Itaara', 2),
    ('Itacurubi', 2),
    ('Itapuca', 2),
    ('Itaqui', 2),
    ('Itati', 2),
    ('Itatiba do Sul', 2),
    ('Ivorá', 2),
    ('Ivoti', 2),
    ('Jaboticaba', 2),
    ('Jacuizinho', 2),
    ('Jacutinga', 2),
    ('Jaguarão', 2),
    ('Jaguari', 2),
    ('Jaquirana', 2),
    ('Jari', 2),
    ('Jóia', 2),
    ('Júlio de Castilhos', 2),
    ('Lagoa Bonita do Sul', 2),
    ('Lagoa dos Três Cantos', 2),
    ('Lagoa Vermelha', 2),
    ('Lagoão', 2),
    ('Lajeado', 2),
    ('Lajeado do Bugre', 2),
    ('Lavras do Sul', 2),
    ('Liberato Salzano', 2),
    ('Lindolfo Collor', 2),
    ('Linha Nova', 2),
    ('Maçambara', 2),
    ('Machadinho', 2),
    ('Mampituba', 2),
    ('Manoel Viana', 2),
    ('Maquiné', 2),
    ('Maratá', 2),
    ('Marau', 2),
    ('Marcelino Ramos', 2),
    ('Mariana Pimentel', 2),
    ('Mariano Moro', 2),
    ('Marques de Souza', 2),
    ('Mata', 2),
    ('Mato Castelhano', 2),
    ('Mato Leitão', 2),
    ('Mato Queimado', 2),
    ('Maximiliano de Almeida', 2),
    ('Minas do Leão', 2),
    ('Miraguaí', 2),
    ('Montauri', 2),
    ('Monte Alegre dos Campos', 2),
    ('Monte Belo do Sul', 2),
    ('Montenegro', 2),
    ('Mormaço', 2),
    ('Morrinhos do Sul', 2),
    ('Morro Redondo', 2),
    ('Morro Reuter', 2),
    ('Mostardas', 2),
    ('Muçum', 2),
    ('Muitos Capões', 2),
    ('Muliterno', 2),
    ('Não-Me-Toque', 2),
    ('Nicolau Vergueiro', 2),
    ('Nonoai', 2),
    ('Nova Alvorada', 2),
    ('Nova Araçá', 2),
    ('Nova Bassano', 2),
    ('Nova Boa Vista', 2),
    ('Nova Bréscia', 2),
    ('Nova Candelária', 2),
    ('Nova Esperança do Sul', 2),
    ('Nova Hartz', 2),
    ('Nova Pádua', 2),
    ('Nova Palma', 2),
    ('Nova Petrópolis', 2),
    ('Nova Prata', 2),
    ('Nova Ramada', 2),
    ('Nova Roma do Sul', 2),
    ('Nova Santa Rita', 2),
    ('Novo Barreiro', 2),
    ('Novo Cabrais', 2),
    ('Novo Hamburgo', 2),
    ('Novo Machado', 2),
    ('Novo Tiradentes', 2),
    ('Novo Xingu', 2),
    ('Osório', 2),
    ('Paim Filho', 2),
    ('Palmares do Sul', 2),
    ('Palmeira das Missões', 2),
    ('Palmitinho', 2),
    ('Panambi', 2),
    ('Pantano Grande', 2),
    ('Paraí', 2),
    ('Paraíso do Sul', 2),
    ('Pareci Novo', 2),
    ('Parobé', 2),
    ('Passa Sete', 2),
    ('Passo do Sobrado', 2),
    ('Passo Fundo', 2),
    ('Paulo Bento', 2),
    ('Paverama', 2),
    ('Pedras Altas', 2),
    ('Pedro Osório', 2),
    ('Pejuçara', 2),
    ('Pelotas', 2),
    ('Picada Café', 2),
    ('Pinhal', 2),
    ('Pinhal da Serra', 2),
    ('Pinhal Grande', 2),
    ('Pinheirinho do Vale', 2),
    ('Pinheiro Machado', 2),
    ('Pirapó', 2),
    ('Piratini', 2),
    ('Planalto', 2),
    ('Poço das Antas', 2),
    ('Pontão', 2),
    ('Ponte Preta', 2),
    ('Portão', 2),
    ('Porto Alegre', 2),
    ('Porto Lucena', 2),
    ('Porto Mauá', 2),
    ('Porto Vera Cruz', 2),
    ('Porto Xavier', 2),
    ('Pouso Novo', 2),
    ('Presidente Lucena', 2),
    ('Progresso', 2),
    ('Protásio Alves', 2),
    ('Putinga', 2),
    ('Quaraí', 2),
    ('Quatro Irmãos', 2),
    ('Quevedos', 2),
    ('Quinze de Novembro', 2),
    ('Redentora', 2),
    ('Relvado', 2),
    ('Restinga Seca', 2),
    ('Rio dos Índios', 2),
    ('Rio Grande', 2),
    ('Rio Pardo', 2),
    ('Riozinho', 2),
    ('Roca Sales', 2),
    ('Rodeio Bonito', 2),
    ('Rolador', 2),
    ('Rolante', 2),
    ('Ronda Alta', 2),
    ('Rondinha', 2),
    ('Roque Gonzales', 2),
    ('Rosário do Sul', 2),
    ('Sagrada Família', 2),
    ('Saldanha Marinho', 2),
    ('Salto do Jacuí', 2),
    ('Salvador das Missões', 2),
    ('Salvador do Sul', 2),
    ('Sananduva', 2),
    ('Santa Bárbara do Sul', 2),
    ('Santa Cecília do Sul', 2),
    ('Santa Clara do Sul', 2),
    ('Santa Cruz do Sul', 2),
    ('Santa Margarida do Sul', 2),
    ('Santa Maria', 2),
    ('Santa Maria do Herval', 2),
    ('Santa Rosa', 2),
    ('Santa Tereza', 2),
    ('Santa Vitória do Palmar', 2),
    ('Santana da Boa Vista', 2),
    ('Santana do Livramento', 2),
    ('Santiago', 2),
    ('Santo Ângelo', 2),
    ('Santo Antônio da Patrulha', 2),
    ('Santo Antônio das Missões', 2),
    ('Santo Antônio do Palma', 2),
    ('Santo Antônio do Planalto', 2),
    ('Santo Augusto', 2),
    ('Santo Cristo', 2),
    ('Santo Expedito do Sul', 2),
    ('São Borja', 2),
    ('São Domingos do Sul', 2),
    ('São Francisco de Assis', 2),
    ('São Francisco de Paula', 2),
    ('São Gabriel', 2),
    ('São Jerônimo', 2),
    ('São João da Urtiga', 2),
    ('São João do Polêsine', 2),
    ('São Jorge', 2),
    ('São José das Missões', 2),
    ('São José do Herval', 2),
    ('São José do Hortêncio', 2),
    ('São José do Inhacorá', 2),
    ('São José do Norte', 2),
    ('São José do Ouro', 2),
    ('São José do Sul', 2),
    ('São José dos Ausentes', 2),
    ('São Leopoldo', 2),
    ('São Lourenço do Sul', 2),
    ('São Luiz Gonzaga', 2),
    ('São Marcos', 2),
    ('São Martinho', 2),
    ('São Martinho da Serra', 2),
    ('São Miguel das Missões', 2),
    ('São Nicolau', 2),
    ('São Paulo das Missões', 2),
    ('São Pedro da Serra', 2),
    ('São Pedro das Missões', 2),
    ('São Pedro do Butiá', 2),
    ('São Pedro do Sul', 2),
    ('São Sebastião do Caí', 2),
    ('São Sepé', 2),
    ('São Valentim', 2),
    ('São Valentim do Sul', 2),
    ('São Valério do Sul', 2),
    ('São Vendelino', 2),
    ('São Vicente do Sul', 2),
    ('Sapiranga', 2),
    ('Sapucaia do Sul', 2),
    ('Sarandi', 2),
    ('Seberi', 2),
    ('Sede Nova', 2),
    ('Segredo', 2),
    ('Selbach', 2),
    ('Senador Salgado Filho', 2),
    ('Sentinela do Sul', 2),
    ('Serafina Corrêa', 2),
    ('Sério', 2),
    ('Sertão', 2),
    ('Sertão Santana', 2),
    ('Sete de Setembro', 2),
    ('Severiano de Almeida', 2),
    ('Silveira Martins', 2),
    ('Sinimbu', 2),
    ('Sobradinho', 2),
    ('Soledade', 2),
    ('Tabaí', 2),
    ('Tapejara', 2),
    ('Tapera', 2),
    ('Tapes', 2),
    ('Taquara', 2),
    ('Taquari', 2),
    ('Taquaruçu do Sul', 2),
    ('Tavares', 2),
    ('Tenente Portela', 2),
    ('Terra de Areia', 2),
    ('Teutônia', 2),
    ('Tio Hugo', 2),
    ('Tiradentes do Sul', 2),
    ('Toropi', 2),
    ('Torres', 2),
    ('Tramandaí', 2),
    ('Travesseiro', 2),
    ('Três Arroios', 2),
    ('Três Cachoeiras', 2),
    ('Três Coroas', 2),
    ('Três de Maio', 2),
    ('Três Forquilhas', 2),
    ('Três Palmeiras', 2),
    ('Três Passos', 2),
    ('Trindade do Sul', 2),
    ('Triunfo', 2),
    ('Tucunduva', 2),
    ('Tunas', 2),
    ('Tupanci do Sul', 2),
    ('Tupanciretã', 2),
    ('Tupandi', 2),
    ('Tuparendi', 2),
    ('Turuçu', 2),
    ('Ubiretama', 2),
    ('União da Serra', 2),
    ('Unistalda', 2),
    ('Uruguaiana', 2),
    ('Vacaria', 2),
    ('Vale do Sol', 2),
    ('Vale Real', 2),
    ('Vale Verde', 2),
    ('Vanini', 2),
    ('Venâncio Aires', 2),
    ('Vera Cruz', 2),
    ('Veranópolis', 2),
    ('Vespasiano Correa', 2),
    ('Viadutos', 2),
    ('Viamão', 2),
    ('Vicente Dutra', 2),
    ('Victor Graeff', 2),
    ('Vila Flores', 2),
    ('Vila Lângaro', 2),
    ('Vila Maria', 2),
    ('Vila Nova do Sul', 2),
    ('Vista Alegre', 2),
    ('Vista Alegre do Prata', 2),
    ('Vista Gaúcha', 2),
    ('Vitória das Missões', 2),
    ('Westfália', 2),
    ('Xangri-lá', 2),
    ('Abdon Batista', 3),
    ('Abelardo Luz', 3),
    ('Agrolândia', 3),
    ('Agronômica', 3),
    ('Água Doce', 3),
    ('Águas de Chapecó', 3),
    ('Águas Frias', 3),
    ('Águas Mornas', 3),
    ('Alfredo Wagner', 3),
    ('Alto Bela Vista', 3),
    ('Anchieta', 3),
    ('Angelina', 3),
    ('Anita Garibaldi', 3),
    ('Anitápolis', 3),
    ('Antônio Carlos', 3),
    ('Apiúna', 3),
    ('Arabutã', 3),
    ('Araquari', 3),
    ('Araranguá', 3),
    ('Armazém', 3),
    ('Arroio Trinta', 3),
    ('Arvoredo', 3),
    ('Ascurra', 3),
    ('Atalanta', 3),
    ('Aurora', 3),
    ('Balneário Arroio do Silva', 3),
    ('Balneário Barra do Sul', 3),
    ('Balneário Camboriú', 3),
    ('Balneário Gaivota', 3),
    ('Bandeirante', 3),
    ('Barra Bonita', 3),
    ('Barra Velha', 3),
    ('Bela Vista do Toldo', 3),
    ('Belmonte', 3),
    ('Benedito Novo', 3),
    ('Biguaçu', 3),
    ('Blumenau', 3),
    ('Bocaina do Sul', 3),
    ('Bom Jardim da Serra', 3),
    ('Bom Jesus', 3),
    ('Bom Jesus do Oeste', 3),
    ('Bom Retiro', 3),
    ('Bombinhas', 3),
    ('Botuverá', 3),
    ('Braço do Norte', 3),
    ('Braço do Trombudo', 3),
    ('Brunópolis', 3),
    ('Brusque', 3),
    ('Caçador', 3),
    ('Caibi', 3),
    ('Calmon', 3),
    ('Camboriú', 3),
    ('Campo Alegre', 3),
    ('Campo Belo do Sul', 3),
    ('Campo Erê', 3),
    ('Campos Novos', 3),
    ('Canelinha', 3),
    ('Canoinhas', 3),
    ('Capão Alto', 3),
    ('Capinzal', 3),
    ('Capivari de Baixo', 3),
    ('Catanduvas', 3),
    ('Caxambu do Sul', 3),
    ('Celso Ramos', 3),
    ('Cerro Negro', 3),
    ('Chapadão do Lageado', 3),
    ('Chapecó', 3),
    ('Cocal do Sul', 3),
    ('Concórdia', 3),
    ('Cordilheira Alta', 3),
    ('Coronel Freitas', 3),
    ('Coronel Martins', 3),
    ('Correia Pinto', 3),
    ('Corupá', 3),
    ('Criciúma', 3),
    ('Cunha Porã', 3),
    ('Cunhataí', 3),
    ('Curitibanos', 3),
    ('Descanso', 3),
    ('Dionísio Cerqueira', 3),
    ('Dona Emma', 3),
    ('Doutor Pedrinho', 3),
    ('Entre Rios', 3),
    ('Ermo', 3),
    ('Erval Velho', 3),
    ('Faxinal dos Guedes', 3),
    ('Flor do Sertão', 3),
    ('Florianópolis', 3),
    ('Formosa do Sul', 3),
    ('Forquilhinha', 3),
    ('Fraiburgo', 3),
    ('Frei Rogério', 3),
    ('Galvão', 3),
    ('Garopaba', 3),
    ('Garuva', 3),
    ('Gaspar', 3),
    ('Governador Celso Ramos', 3),
    ('Grão Pará', 3),
    ('Gravatal', 3),
    ('Guabiruba', 3),
    ('Guaraciaba', 3),
    ('Guaramirim', 3),
    ('Guarujá do Sul', 3),
    ('Guatambú', 3),
    ('Herval dOeste', 3),
    ('Ibiam', 3),
    ('Ibicaré', 3),
    ('Ibirama', 3),
    ('Içara', 3),
    ('Ilhota', 3),
    ('Imaruí', 3),
    ('Imbituba', 3),
    ('Imbuia', 3),
    ('Indaial', 3),
    ('Iomerê', 3),
    ('Ipira', 3),
    ('Iporã do Oeste', 3),
    ('Ipuaçu', 3),
    ('Ipumirim', 3),
    ('Iraceminha', 3),
    ('Irani', 3),
    ('Irati', 3),
    ('Irineópolis', 3),
    ('Itá', 3),
    ('Itaiópolis', 3),
    ('Itajaí', 3),
    ('Itapema', 3),
    ('Itapiranga', 3),
    ('Itapoá', 3),
    ('Ituporanga', 3),
    ('Jaborá', 3),
    ('Jacinto Machado', 3),
    ('Jaguaruna', 3),
    ('Jaraguá do Sul', 3),
    ('Jardinópolis', 3),
    ('Joaçaba', 3),
    ('Joinville', 3),
    ('José Boiteux', 3),
    ('Jupiá', 3),
    ('Lacerdópolis', 3),
    ('Lages', 3),
    ('Laguna', 3),
    ('Lajeado Grande', 3),
    ('Laurentino', 3),
    ('Lauro Muller', 3),
    ('Lebon Régis', 3),
    ('Leoberto Leal', 3),
    ('Lindóia do Sul', 3),
    ('Lontras', 3),
    ('Luiz Alves', 3),
    ('Luzerna', 3),
    ('Macieira', 3),
    ('Mafra', 3),
    ('Major Gercino', 3),
    ('Major Vieira', 3),
    ('Maracajá', 3),
    ('Maravilha', 3),
    ('Marema', 3),
    ('Massaranduba', 3),
    ('Matos Costa', 3),
    ('Meleiro', 3),
    ('Mirim Doce', 3),
    ('Modelo', 3),
    ('Mondaí', 3),
    ('Monte Carlo', 3),
    ('Monte Castelo', 3),
    ('Morro da Fumaça', 3),
    ('Morro Grande', 3),
    ('Navegantes', 3),
    ('Nova Erechim', 3),
    ('Nova Itaberaba', 3),
    ('Nova Trento', 3),
    ('Nova Veneza', 3),
    ('Novo Horizonte', 3),
    ('Orleans', 3),
    ('Otacílio Costa', 3),
    ('Ouro', 3),
    ('Ouro Verde', 3),
    ('Paial', 3),
    ('Painel', 3),
    ('Palhoça', 3),
    ('Palma Sola', 3),
    ('Palmeira', 3),
    ('Palmitos', 3),
    ('Papanduva', 3),
    ('Paraíso', 3),
    ('Passo de Torres', 3),
    ('Passos Maia', 3),
    ('Paulo Lopes', 3),
    ('Pedras Grandes', 3),
    ('Penha', 3),
    ('Peritiba', 3),
    ('Petrolândia', 3),
    ('Piçarras', 3),
    ('Pinhalzinho', 3),
    ('Pinheiro Preto', 3),
    ('Piratuba', 3),
    ('Planalto Alegre', 3),
    ('Pomerode', 3),
    ('Ponte Alta', 3),
    ('Ponte Alta do Norte', 3),
    ('Ponte Serrada', 3),
    ('Porto Belo', 3),
    ('Porto União', 3),
    ('Pouso Redondo', 3),
    ('Praia Grande', 3),
    ('Presidente Castelo Branco', 3),
    ('Presidente Getúlio', 3),
    ('Presidente Nereu', 3),
    ('Princesa', 3),
    ('Quilombo', 3),
    ('Rancho Queimado', 3),
    ('Rio das Antas', 3),
    ('Rio do Campo', 3),
    ('Rio do Oeste', 3),
    ('Rio do Sul', 3),
    ('Rio dos Cedros', 3),
    ('Rio Fortuna', 3),
    ('Rio Negrinho', 3),
    ('Rio Rufino', 3),
    ('Riqueza', 3),
    ('Rodeio', 3),
    ('Romelândia', 3),
    ('Salete', 3),
    ('Saltinho', 3),
    ('Salto Veloso', 3),
    ('Sangão', 3),
    ('Santa Cecília', 3),
    ('Santa Helena', 3),
    ('Santa Rosa de Lima', 3),
    ('Santa Rosa do Sul', 3),
    ('Santa Terezinha', 3),
    ('Santa Terezinha do Progresso', 3),
    ('Santiago do Sul', 3),
    ('Santo Amaro da Imperatriz', 3),
    ('São Bento do Sul', 3),
    ('São Bernardino', 3),
    ('São Bonifácio', 3),
    ('São Carlos', 3),
    ('São Cristovão do Sul', 3),
    ('São Domingos', 3),
    ('São Francisco do Sul', 3),
    ('São João Batista', 3),
    ('São João do Itaperiú', 3),
    ('São João do Oeste', 3),
    ('São João do Sul', 3),
    ('São Joaquim', 3),
    ('São José', 3),
    ('São José do Cedro', 3),
    ('São José do Cerrito', 3),
    ('São Lourenço do Oeste', 3),
    ('São Ludgero', 3),
    ('São Martinho', 3),
    ('São Miguel da Boa Vista', 3),
    ('São Miguel do Oeste', 3),
    ('São Pedro de Alcântara', 3),
    ('Saudades', 3),
    ('Schroeder', 3),
    ('Seara', 3),
    ('Serra Alta', 3),
    ('Siderópolis', 3),
    ('Sombrio', 3),
    ('Sul Brasil', 3),
    ('Taió', 3),
    ('Tangará', 3),
    ('Tigrinhos', 3),
    ('Tijucas', 3),
    ('Timbé do Sul', 3),
    ('Timbó', 3),
    ('Timbó Grande', 3),
    ('Três Barras', 3),
    ('Treviso', 3),
    ('Treze de Maio', 3),
    ('Treze Tílias', 3),
    ('Trombudo Central', 3),
    ('Tubarão', 3),
    ('Tunápolis', 3),
    ('Turvo', 3),
    ('União do Oeste', 3),
    ('Urubici', 3),
    ('Urupema', 3),
    ('Urussanga', 3),
    ('Vargeão', 3),
    ('Vargem', 3),
    ('Vargem Bonita', 3),
    ('Vidal Ramos', 3),
    ('Videira', 3),
    ('Vitor Meireles', 3),
    ('Witmarsum', 3),
    ('Xanxerê', 3),
    ('Xavantina', 3),
    ('Xaxim', 3),
    ('Zortéa', 3);

